import Link from 'next/link';

async function getSignals() {
  try {
    const response = await fetch('http://localhost:3001/v1/signals', { cache: 'no-store' });
    if (!response.ok) return [];
    const data = await response.json();
    return data.items || [];
  } catch {
    return [];
  }
}

export default async function SignalsPage() {
  const signals = await getSignals();

  return (
    <main>
      <h1>Intelligence Signals</h1>
      <p style={{ color: 'var(--text-secondary)' }}>
        Live signal stream generated by the SWAT intelligence layer.
      </p>

      <div className="grid" style={{ gridTemplateColumns: '1fr' }}>
        {signals.length === 0 ? (
          <div className="card" style={{ textAlign: 'center', padding: '3rem' }}>
            <p style={{ color: 'var(--text-secondary)' }}>No active signals detected. The engine is monitoring.</p>
          </div>
        ) : (
          signals.map((signal: any) => (
            <div key={signal.id} className="card" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <div>
                <h3 style={{ marginBottom: '0.5rem', color: 'var(--accent)' }}>{signal.pattern_type.toUpperCase()} SIGNAL</h3>
                <p style={{ margin: '0 0 0.5rem 0' }}>
                  <strong>Token:</strong> {signal.token_mint} <br/>
                  <strong>Cluster:</strong> {signal.cluster_id}
                </p>
                <div>
                  <span className="badge warning" style={{ marginRight: '0.5rem' }}>Confidence: {signal.confidence}%</span>
                  <span className="badge success">Score: {signal.signal_score}</span>
                </div>
              </div>
              <div style={{ textAlign: 'right' }}>
                <p style={{ color: 'var(--text-secondary)', fontSize: '0.875rem' }}>
                  {new Date(signal.created_at).toLocaleString()}
                </p>
              </div>
            </div>
          ))
        )}
      </div>
    </main>
  );
}
